---
title: "Statisitcal Programming - 2020 - Project 1"
output: rmarkdown::html_document
author: Add your name here
---

Due on Monday, November 2nd by 5:00 pm (17:00), UK local time.

Before you start be sure to read through *all* of the rules and instructions in the `README.md`.

<br/>

### Data

```{r}
library(tidyverse)
f1 = readRDS(file="data/f1.rds")
```


<br/>

### Task 1 - Tidy the data

#### Write up

<!-- Include write up here -->

#### Code

```{r task1}
f1_tbl = tibble(f1_data = f1) %>%
  unnest_wider(f1_data) %>%
  hoist(
    MRData,
    races = c('RaceTable', 'Races')
  ) %>% select(races) %>%
  unnest_longer(races) %>%
  hoist(
    races,
    race_name = c('raceName'),
    round = c('round'),
    date = (c('date')),
    results = c('Results')
  ) %>% select(-races) %>%
  unnest_longer(results) %>%
  hoist(
    results,
    first_name = c('Driver', 'givenName'),
    last_name = c('Driver', 'familyName'),
    constructor = c('Constructor', 'constructorId'),
    position = c('positionText'),
    points = c('points')
    ) %>%
  mutate(
    round = as.integer(round),
    date = as.Date(date),
    driver = paste(first_name, last_name),
    position = as.integer(position),
    points = as.integer(points),
    warning = FALSE
  ) %>% 
  select(race_name, round, date, driver, constructor, position, points)
f1_tbl
```

<br/>


### Task 2 - Drivers' Championship

#### Write up

<!-- Include write up here -->

#### Code

```{r task2}

```

<br/>

### Task 3 - Cumulative Constructors

#### Write up

<!-- Include write up here -->

#### Code

```{r task3}

```

<br/>

### Task 4 - Visualization

#### Write up

<!-- Include write up here -->

#### Code

```{r task4}

```

<br/>

